### ISSUE TITLE
Out of sync set point and current temp

### ISSUE THREAD

**Issue by tmchow** [dlarrick/hass-kumo#29]
I’m having weird issues with the HA reporting different set point and current temp compared to the kumo app. 

![105FB7D6-BD14-4D84-BD5D-B95CF128AF21](https://user-images.githubusercontent.com/517103/83342273-4ab50380-a2a2-11ea-934d-90acaa1de905.jpeg)
![Uploading 5D4F686A-FCD0-4790-836A-4520C4E35859.png…]()

**Comment by dlarrick** [comment]
Not seeing your 2nd image (presumably a KumoCloud screenshot).

My advice: stop trying to use HA and KumoCloud app together. They're both polling the indoor units, relatively infrequently. What's more, KumoCloud tries to talk locally to the units (using the same protocol as HA is using), but if it fails it falls back to a cloud API into which we have no visibility since it's over https. HA only polls climate units once a minute, so if you make a change in KumoCloud (or with a wireless remote), it might not show up in HA for a while.

Another issue might be that the units' API is in Celsius. HA and KumoCloud may be converting differently; I have seen some evidence that KumoCloud app is not actually doing math but instead using a lookup table.

If you'd like to try to debug, my approach would be to take packet captures on your phone while running HA and KumoCloud, and see if you can spot a difference in the responses being returned from the indoor unit. If I'm somehow misinterpreting the data then that can likely be fixed -- unless it's rounding of Celsius; I'm not interested in trying to reverse-engineer their lookup table.

**Comment by tmchow** [comment]
I'm actually only trying to use HA now, but had weirdness where it didn't seem like the temp and set points were updating based on my changes.  Hence, why I went to kumo cloud app to see what was going on, and noticed the difference.  I waited multiple minutes to see if HA would update to reflect what I saw in Kumo cloud app, but it never did.

**Comment by dlarrick** [comment]
Connection refused! Now that's odd. I can think of only a few possibilities:
1. Some sort of rate limiting. Seems unlikely
2. Some sort of firewall between your HA and the unit(s)
3. Power issues / loose connector causing the Kumo WiFi unit to reboot
4. DHCP lease changes
5. IP address conflict (multiple machines on your network with the same IP address)

I highly recommend setting up a static / persistent DHCP lease for the Kumo units, if your router supports it.

**Comment by tmchow** [comment]
- I have a static IP for both units and I don't see any IP conflicts (I'm using `192.168.1.145` and `192.168.1.146`).
- I've had 520 occurrences of this error in my HA logs from 11:31am PT to now (12:17pm PT), so less than 1 hour.
- I don't see any indications of power issues, but wondering if there is a good way to detect connect and reconnect.

**Comment by dlarrick** [comment]
"Connection refused" is bad. That means either the service (on the Kumo unit) is not running / not listening, or something (firewall?) in the middle is actively preventing the TCP socket from opening. In TCP terms, something replied with a RST/ACK packet to the HA system's SYN packet.

**Comment by tmchow** [comment]
Sh*t, I have no idea how to troubleshoot this.    I went into my unifi dashboard to see any events and noticed some disconnects that happen at blips for like a minute:

![image](https://user-images.githubusercontent.com/517103/83467831-e2942800-a42f-11ea-8ea3-cf76b4ae0b95.png)

However, I then looked back in logs to look at the timeframe I saw the HA erros (1130am to 1215pm PT) and saw this frequent disconnects with the Attic (name for my home office):

![image](https://user-images.githubusercontent.com/517103/83467968-49194600-a430-11ea-934f-ad9395a2cf9c.png)

So based on this, I'm thinking the issue is the Attic/Office unit, so I'm going to try to get an AP up here.

**Comment by omriasta** [comment]
Not sure if it's the same issue but occasionally there is an issue with the kumo device denying connections to certain local ips. Usually restarting my entire mesh network resolves this for me with Google WiFi. I originally brought this up with the author of the kumojs project. @dlarrick has also seen something similar https://community.home-assistant.io/t/mitsubishi-kumo-cloud-integration/121508/120

**Comment by tmchow** [comment]
Got my new AP in that home office area where the second wall unit it.  Unfortunately I’m still seeing the same connection errors all over my logs. 

Both units have static IPs too

**Comment by omriasta** [comment]
Check if you can ping the devices from your Hass setup. I also noticed this a few times but I was trying to ping from a different device which was getting responses. When I tried to ping from my Hass it was being blocked. Only way I have figured so far is to restart my entire network (all access points). It's possible that just having the AP that Hass or the kumo unit is connected to rebooted may work but I usually just reboot all.

**Comment by tmchow** [comment]
I resolved this issue by creating a separate 2Ghz wifi network. In latest installer manual for Kumo cloud, they specifically say a dual band network can cause network disconnects. After creating a dedicated 2Ghz network, It seems to be resolved.
