### ISSUE TITLE
Left/right fan vanes?

### ISSUE THREAD

**Issue by josh-haas** [dlarrick/hass-kumo#68]
There don't appear to be controls for left/right fan vanes in here. Is control of this accessible to this integration?

**Comment by omriasta** [comment]
I don't believe so but this most likely would need to be added to [pykumo](https://github.com/dlarrick/pykumo) first....
I don't believe any of us have a unit with this feature so we would probably need your cache file first to see how it gets reported...please make sure you remove all personal data from the cache file before sending it and maybe best to open a new topic under [pykumo](https://github.com/dlarrick/pykumo) first

**Comment by mikeygnyc** [comment]
I have a unit that has these controls on the physical remote but they are not even available on Kumo cloud. I don't think the underlying API exposes this to begin with.

**Comment by dlarrick** [comment]
I think it should be possible, but as @omriasta says none of us has an indoor unit with controllable left/right vane directions.
If you're savvy with Python it should be possible to create a PyKumo object using the pykumo library directly and get the raw status returned from the indoor unit, and examine it to see what left/right swing is called. Then we can add support for it to PyKumo, and see if we can hook this up to the HA climate object or otherwise make it available.

**Comment by danielgoepp** [comment]
As @mikeygnyc says, I am pretty sure this is not possible. All my units have this feature and I can set it on the remote, I just checked the status via the API and I don't see it:

```
{ 
  'roomTemp': 20, 
  'mode': 'off', 
  'spCool': 21.5, 
  'spHeat': 23, 
  'vaneDir': 'vertical', 
  'fanSpeed': 'superPowerful', 
  'tempSource': 'sensor0', 
  'activeThermistor': 'sensor0', 
  'filterDirty': False, 
  'hotAdjust': False, 
  'defrost': False, 
  'standby': False, 
  'runTest': 0
}
```

**Comment by dlarrick** [comment]
I have added some notes in the pykumo repo's README about how to use pykumo library interactively. If you can discover some way the left/right vanes are exposed in the indoor units' API, we can support them. If so, please open another ticket in https://github.com/dlarrick/pykumo with details. For now I'm closing this one.
