### ISSUE TITLE
entities tagged with incorrect integration

### ISSUE THREAD

**Issue by dBeau** [dlarrick/hass-kumo#78]
Initial install went well and all seems functional.  My system has six inside units.  Only the first entity was tagged with 'Kumo' as the integration.  The remaining  entities were tagged with 'Climate' as the integration.  

Full disclosure... of my six units, the wifi device is broken on one of them so it didnt have a IP address registered.  When prompted to enter one, I just made one up.  This, reasonably enough, caused only five climate entities to be created.   I only mention this because I suspect it is a bit outside of the normal flow.

Thanks for a great integration!
--Don

**Comment by omriasta** [comment]
I'm not sure what you mean by tagged as kumo but my guess is the failed unit could be interrupting the config flow. Any reason why you can't remove it from the kumo account? I assume that if the wifi is broken it doesn't work in the kumo app either, you would just have to remove it from there and then also make sure that you delete the kumo cache file (not sure if that happens when you delete the integration or not)

**Comment by dlarrick** [comment]
When you says "tagged with Kumo" where are you looking? I don't see how it could possibly be working if the units aren't associated with the integration. Have you tried restarting HA?

If your IP addresses will be stable and you understand JSON syntax, you could make sure "Prefer Cache" is turned on, and remove any mention of your missing unit from the kumo_cache.json. Then restart HA.

**Comment by dlarrick** [comment]
Thanks, closing.
